# For ruby 1.8 support
Style/HashSyntax:
  EnforcedStyle: 'hash_rockets'
Style/SymbolProc:
  Enabled: false

# Because it's just silly for this file
Style/Documentation:
  Exclude:
    - lib/oembed/version.rb
    - lib/oembed/providers/**/*.rb

# Our gemspec is long. That's ok.
Metrics/LineLength:
  Exclude:
    - ruby-oembed.gemspec
