Style/HashSyntax:
  EnforcedStyle: 'hash_rockets'
Style/SpecialGlobalVars:
  Enabled: false
Style/Documentation:
  Exclude:
    - lib/oembed/version.rb

Metrics/LineLength:
  Exclude:
    - ruby-oembed.gemspec